    bucket = "mcma-dotnet-tfstate"
    key    = "Mcma.Aws.Services.ServiceRegistry.tfstate"
    region = "us-east-1"
	access_key = "AKIAJG6HOYLVWQXVKRWA"
	secret_key = "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"
